#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = "purge" ]; then
  rm -rf /var/lib/fbootd
  if getent passwd fbootd >/dev/null; then
    deluser --system fbootd >/dev/null 2>&1 || true
  fi
  if getent group fbootd >/dev/null; then
    delgroup --system fbootd >/dev/null 2>&1 || true
  fi
fi

exit 0
