#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  systemctl stop fbootd.service >/dev/null 2>&1 || true
fi

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  if [ -d /run/systemd/system ]; then
    systemctl disable fbootd.service >/dev/null 2>&1 || true
  fi
fi

exit 0
